/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class elastos_china_com_elastossample_JniUtils */

#ifndef _Included_elastos_china_com_elastossample_JniUtils
#define _Included_elastos_china_com_elastossample_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     elastos_china_com_elastossample_JniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_elastos_china_com_elastossample_JniUtils_getCLanguageString
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_elastos_china_com_elastossample_JniUtils_getElastosString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif


