set(CURRENT_MIRROR_SOURCES
    _Elastos_Core_CObject.cpp
    Elastos_Core_CObjectClassObject.cpp
    _Elastos_Core_CThread.cpp
    Elastos_Core_CThreadClassObject.cpp
    _Elastos_Core_CThreadGroup.cpp
    Elastos_Core_CThreadGroupClassObject.cpp
    _Elastos_Core_CPathClassLoader.cpp
    Elastos_Core_CPathClassLoaderClassObject.cpp
    _Elastos_Core_CString.cpp
    Elastos_Core_CStringClassObject.cpp
    _Elastos_Core_CBoolean.cpp
    Elastos_Core_CBooleanClassObject.cpp
    _Elastos_Core_CByte.cpp
    Elastos_Core_CByteClassObject.cpp
    _Elastos_Core_CChar32.cpp
    Elastos_Core_CChar32ClassObject.cpp
    _Elastos_Core_CInteger16.cpp
    Elastos_Core_CInteger16ClassObject.cpp
    _Elastos_Core_CInteger32.cpp
    Elastos_Core_CInteger32ClassObject.cpp
    _Elastos_Core_CInteger64.cpp
    Elastos_Core_CInteger64ClassObject.cpp
    _Elastos_Core_CFloat.cpp
    Elastos_Core_CFloatClassObject.cpp
    _Elastos_Core_CDouble.cpp
    Elastos_Core_CDoubleClassObject.cpp
    _Elastos_Core_CArrayOf.cpp
    Elastos_Core_CArrayOfClassObject.cpp
    _Elastos_Math_CBigDecimal.cpp
    Elastos_Math_CBigDecimalClassObject.cpp
    _Elastos_Math_CBigDecimalHelper.cpp
    Elastos_Math_CBigDecimalHelperClassObject.cpp
    _Elastos_Math_CBigInteger.cpp
    Elastos_Math_CBigIntegerClassObject.cpp
    _Elastos_Math_CBigIntegerHelper.cpp
    Elastos_Math_CBigIntegerHelperClassObject.cpp
    _Elastos_Math_CMathContext.cpp
    Elastos_Math_CMathContextClassObject.cpp
    _Elastos_Math_CMathContextHelper.cpp
    Elastos_Math_CMathContextHelperClassObject.cpp
    _Elastos_IO_CPlainFile.cpp
    Elastos_IO_CPlainFileClassObject.cpp
    _Elastos_Utility_CStringTokenizer.cpp
    Elastos_Utility_CStringTokenizerClassObject.cpp
    _Elastos_Utility_CArrayDeque.cpp
    Elastos_Utility_CArrayDequeClassObject.cpp
    _Elastos_Utility_CArrayList.cpp
    Elastos_Utility_CArrayListClassObject.cpp
    _Elastos_Utility_CArrayListIterator.cpp
    Elastos_Utility_CArrayListIteratorClassObject.cpp
    _Elastos_Utility_CSimpleListIterator.cpp
    Elastos_Utility_CSimpleListIteratorClassObject.cpp
    _Elastos_Utility_CFullListIterator.cpp
    Elastos_Utility_CFullListIteratorClassObject.cpp
    _Elastos_Utility_CSubAbstractListIterator.cpp
    Elastos_Utility_CSubAbstractListIteratorClassObject.cpp
    _Elastos_Utility_CSubAbstractList.cpp
    Elastos_Utility_CSubAbstractListClassObject.cpp
    _Elastos_Utility_CRandomAccessSubList.cpp
    Elastos_Utility_CRandomAccessSubListClassObject.cpp
    _Elastos_Utility_CBitSet.cpp
    Elastos_Utility_CBitSetClassObject.cpp
    _Elastos_Utility_CBitSetHelper.cpp
    Elastos_Utility_CBitSetHelperClassObject.cpp
    _Elastos_Utility_CEnumMap.cpp
    Elastos_Utility_CEnumMapClassObject.cpp
    _Elastos_Utility_CHashMap.cpp
    Elastos_Utility_CHashMapClassObject.cpp
    _Elastos_Utility_CHashSet.cpp
    Elastos_Utility_CHashSetClassObject.cpp
    _Elastos_Utility_CHashTable.cpp
    Elastos_Utility_CHashTableClassObject.cpp
    _Elastos_Utility_CLinkedHashMap.cpp
    Elastos_Utility_CLinkedHashMapClassObject.cpp
    _Elastos_Utility_CLinkedHashSet.cpp
    Elastos_Utility_CLinkedHashSetClassObject.cpp
    _Elastos_Utility_CLinkedList.cpp
    Elastos_Utility_CLinkedListClassObject.cpp
    _Elastos_Utility_CVector.cpp
    Elastos_Utility_CVectorClassObject.cpp
    _Elastos_Utility_CStack.cpp
    Elastos_Utility_CStackClassObject.cpp
    _Elastos_Utility_CWeakHashMap.cpp
    Elastos_Utility_CWeakHashMapClassObject.cpp
    _Elastos_Utility_CTreeMap.cpp
    Elastos_Utility_CTreeMapClassObject.cpp
    _Elastos_Utility_CTreeSet.cpp
    Elastos_Utility_CTreeSetClassObject.cpp
    _Elastos_Utility_CPriorityQueue.cpp
    Elastos_Utility_CPriorityQueueClassObject.cpp
    _Elastos_Utility_CHugeEnumSet.cpp
    Elastos_Utility_CHugeEnumSetClassObject.cpp
    _Elastos_Utility_CMiniEnumSet.cpp
    Elastos_Utility_CMiniEnumSetClassObject.cpp
    _Elastos_Utility_CUnsafeArrayList.cpp
    Elastos_Utility_CUnsafeArrayListClassObject.cpp
    _Elastos_Utility_CCollections.cpp
    Elastos_Utility_CCollectionsClassObject.cpp
    _Elastos_Utility_CEnumSetHelper.cpp
    Elastos_Utility_CEnumSetHelperClassObject.cpp
    _Elastos_Utility_Regex_CMatcher.cpp
    Elastos_Utility_Regex_CMatcherClassObject.cpp
    _Elastos_Utility_Regex_CMatcherHelper.cpp
    Elastos_Utility_Regex_CMatcherHelperClassObject.cpp
    _Elastos_Utility_Regex_CSplitter.cpp
    Elastos_Utility_Regex_CSplitterClassObject.cpp
    _Elastos_Utility_Regex_CPatternHelper.cpp
    Elastos_Utility_Regex_CPatternHelperClassObject.cpp
    _Elastos.CoreLibrarypub.cpp
    _Elastos.CoreLibraryabrg.cpp
)
